WebMG/Areas/SuperAdmin/Controllers/CenterController.cs
using MG.DataAccess.Repository.IRepository;
using MG.Models;
using MGWeb.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebMG.Data;
using WebMG.Models;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory.Database;

namespace MGWeb.Areas.SuperAdmin.Controllers
{
    [Area("SuperAdmin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class CenterController : Controller
    {
        //  private readonly MGDbContext _db;
        // private readonly ICenterRepository _centerRepo;

        private readonly IUnitOfWork _unitOfWork;
        public CenterController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        //public CenterController(ICenterRepository db)
        //{
        //    _centerRepo = db;
        //}
        public IActionResult Index()
        {
            // List<Center> objCenterList = _unitOfWork.Centers.GetAll().ToList();
            //return View(objCenterList);
            List<Center> objCenterList = _unitOfWork.Center.GetAll().ToList();
            return View(objCenterList);
        }
        //public IActionResult Create()
        //{
        //    return View();
        //}
        //public IActionResult Upsert(int? id)
        //{

        //    if (id == null || id == 0)
        //    {
        //        //create
        //        return View(new Center());
        //    }
        //    else
        //    {
        //        //update
        //        Center centerObj = _unitOfWork.Center.Get(u => u.Id == id);
        //        return View(centerObj);
        //    }
        //}
        //[HttpPost]
        //public IActionResult Upsert(Center CenterObj)
        //{
        //    if (ModelState.IsValid)
        //    {

        //        if (CenterObj.Id == 0)
        //        {
        //            _unitOfWork.Center.Add(CenterObj);
        //        }
        //        else
        //        {
        //            _unitOfWork.Center.Update(CenterObj);
        //        }

        //        _unitOfWork.Save();
        //        TempData["success"] = "Company created successfully";
        //        return RedirectToAction("Index");
        //    }
        //    else
        //    {

        //        return View(CenterObj);
        //    }
        //}
        //public IActionResult Create(Center obj)
        //{
        //    if (obj.Name == obj.DisplayOrder.ToString())
        //    {
        //        ModelState.AddModelError("name", "The DisplayOrder cannot exactly match the Name.");
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        _unitOfWork.Center.Add(obj);
        //        _unitOfWork.Save();
        //        TempData["success"] = "Center created successfully";
        //        return RedirectToAction("Index");
        //    }
        //    return View();

        //}
        ////public IActionResult Edit(int? id)
        //{
        //    if (id == null || id == 0)
        //    {
        //        return NotFound();
        //    }
        //    Center? centerFromDb = _unitOfWork.Center.Get(u => u.Id == id);
        //    //Category? categoryFromDb1 = _db.Categories.FirstOrDefault(u=>u.Id==id);
        //    //Category? categoryFromDb2 = _db.Categories.Where(u=>u.Id==id).FirstOrDefault();

        //    if (centerFromDb == null)
        //    {
        //        return NotFound();
        //    }
        //    return View(centerFromDb);
        //}

        //[HttpPost]
        //public IActionResult Edit(Center obj)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _unitOfWork.Center.Update(obj);
        //        _unitOfWork.Save();
        //        TempData["success"] = "Center updated successfully";
        //        return RedirectToAction("Index");
        //    }
        //    return View();

        //}

        //  [HttpPost, ActionName("Delete")]
        //public IActionResult DeletePOST(int? id)
        //{
        //    Center? obj = _unitOfWork.Center.Get(u => u.Id == id);
        //    if (obj == null)
        //    {
        //        return NotFound();
        //    }
        //    _unitOfWork.Center.Remove(obj);
        //    _unitOfWork.Save();
        //    TempData["success"] = "Center deleted successfully";
        //    return RedirectToAction("Index");
        //}
        #region API CALLS

        [HttpGet]
        public IActionResult GetAll()
        {
            List<Center> objCompanyList = _unitOfWork.Center.GetAll().ToList();
            return Json(new { data = objCompanyList });
        }
        #endregion

    }
}

WebMG/Areas/SuperAdmin/Views/Center/Create.cshtml
@using MG.Models﻿
@model Center

<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
    <div class="row">
        <div class="col-12 text-center">
                <h2 class="text-white py-2">Create Center</h2>
        </div>
    </div>
    </div>
    <div class="card-body p-4">
        <form method="post" class="row">
            <div class="border p-3">
                @*<div asp-validation-summary="ModelOnly"></div>*@
                <div class="form-floating py-2 col-12">
                    <input asp-for="Name" class="form-control border-0 shadow" />
                    <label asp-for="Name" class="ms-2"></label>
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="DisplayOrder" class="form-control border-0 shadow" />
                    <label asp-for="DisplayOrder" class="ms-2"></label>
                    <span asp-validation-for="DisplayOrder" class="text-danger"></span>
                </div>

                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-primary form-control">Create</button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="Center" asp-action="Index" class="btn btn-outline-primary border  form-control">
                            Back to List
                        </a>
                    </div>
                </div>


            </div>
        </form>
    </div>
</div>




@section Scripts{
    @{
    <partial name="_ValidationScriptsPartial"/>
    }
}

WebMG/Areas/SuperAdmin/Views/Center/Index.cshtml
@using MG.Models
@model List<Center>
<h1>Center List</h1>
<table class="table table-bordered table-striped">
    <thead>
    <tr>
        <th> 
            Center Name
        </th>
        <th>
            Display Order
        </th>
 

</tr>
    </thead>
    <tbody>
        @foreach(var obj in Model)
        {
            <tr>
                <td>@obj.Name</td>
                <td>
                   @obj.DisplayOrder
                </td>
            </tr>
        }
      
    </tbody>
</table>
@* <div class="card shadow border-0 my-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Center List</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <div class="row pb-3">
            <div class="col-6">
            </div>
            <div class="col-6 text-end">
                <a asp-controller="Center" asp-action="Upsert" class="btn btn-primary"> <th></th>
                    <i class="bi bi-plus-circle"></i>  Create New Center
                </a>
            </div>
        </div>

        <table id="tblData" class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>Name</th>
                    <th></th>
                </tr>
            </thead>
        </table>

    </div>
</div>

@section Scripts{
    <script src="~/js/company.js"></script>
} *@

WebMG/Areas/SuperAdmin/Views/Center/Upsert.cshtml
@using MG.Models
@model Center

<div class="card shadow border-0 my-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2"> @(Model.Id != 0 ? "Update" : "Create") Company</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post" class="row" enctype="multipart/form-data">
            <input asp-for="Id" hidden />
            <div class="row">
                <div class="col-12">
                    <div class="border p-3">
                        @*<div asp-validation-summary="ModelOnly"></div>*@
                        <div class="form-floating py-2 col-12">
                            <input asp-for="Name" class="form-control border-0 shadow" />
                            <label asp-for="Name" class="ms-2"></label>
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="DisplayOrder" class="form-control border-0 shadow" />
                            <label asp-for="DisplayOrder" class="ms-2"></label>
                            <span asp-validation-for="DisplayOrder" class="text-danger"></span>
                        </div>
                        <div class="row pt-2">
                            <div class="col-6 col-md-3">
                                @if (Model.Id != 0)
                                {
                                    <button type="submit" class="btn btn-primary form-control">Update</button>
                                }
                                else
                                {
                                    <button type="submit" class="btn btn-primary form-control">Create</button>
                                }
                            </div>
                            <div class="col-6 col-md-3">
                                <a asp-controller="Center" asp-action="Index" class="btn btn-outline-primary border  form-control">
                                    Back to List
                                </a>
                            </div>
                        </div>


                    </div>
                </div>

            </div>

        </form>
    </div>
</div>




@section Scripts {
    <script>
        tinymce.init({
            selector: 'textarea',
            plugins: 'anchor autolink charmap codesample emoticons  lists   table visualblocks wordcount',
            toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough |  align lineheight | numlist bullist indent outdent',
        });
    </script>
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}